### ISSUE TITLE
[QUESTION] Why is `systemd-email` so complex ?

### ISSUE THREAD

**Issue by nil0x42** [karlicoss/dron#16]
Hi ! I'm reading your sources with great interest, and i came out to `systemd-email`, and it looks like to me that the same output can be achieved with this single command: `systemctl --user status myFailingUnit.service --lines 99999 -o cat`

Is it really equivalent ?

**Comment by karlicoss** [comment]
Yeah I agree it's more complex that I wish it was :( Mainly  wanted to only include all the logs since the last time job was run, so it's easy to visually overview. Wheras with 99999 lines one would have to scroll and manually find the log boundary? Do you know if there is an easier way to do that by any chance?

**Comment by nil0x42** [comment]
in my machine it looks like it already filters output from last run only. can you test on yours ?

**Comment by karlicoss** [comment]
Wow, indeed, it works, thank you! 
Looks like the key is using `systemctl status`, e.g. `journalctl --user -u dashboard_pub.service --lines 99999 -o cat` does include output of the previous runs

**Comment by karlicoss** [comment]
thanks, fixed now
